name: cypress CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run cypress tests
        uses: actions/setup-node@v3
      - run: npm i
      - run: npm test
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-artifact
          path: |
            cypress/screenshots
            cypress/videos
